// STONK WARS rosters — the 16 contestants of a tournament. The DEV picks which roster the NEXT tournament runs
// (POST /api/stonkwars/roster). Every trader: id (unique across rosters; portrait = public/stonkwars/<id>.png), name,
// emoji, stat (the ranking number behind the "brain #N" label), statText (what the site shows), brain, blurb.
// brain: memory (coins remembered), reactionMs, maxPositions, sizeFrac (bet as a share of cash), impulsivity,
// threshold (score needed to buy), depth (which signals it can see, 0..1), stopPct, takePct, trailPct, maxHoldMin,
// quirk — one engine behaviour: adaptive contrarian conviction echolocate forget greedy grudge hunt mimic multi pack
// shiny steady swarm tools twitchy (see score()/manage() in stonkwars.js).
function fmtNeurons(n) { return (n >= 1e9 ? (n / 1e9).toFixed(n >= 10e9 ? 0 : 1) + 'B' : n >= 1e6 ? (n / 1e6).toFixed(0) + 'M' : Math.round(n / 1e3) + 'K') + ' neurons'; }

// ANIMAL KINGDOM — brains scaled to real neuron counts (the original 16)
const ANIMALS = [
  { id: 'elephant', name: 'Elephant', emoji: '🐘', neurons: 257e9, brain: { memory: 50, reactionMs: 20000, maxPositions: 4, sizeFrac: 0.15, impulsivity: 0.35, threshold: 0.62, depth: 0.85, stopPct: 0.15, takePct: 0.50, trailPct: 0.25, maxHoldMin: 45, quirk: 'grudge' }, blurb: 'Never forgets a rug. Slow to act, refuses to be fooled twice.' },
  { id: 'orca', name: 'Orca', emoji: '🐋', neurons: 43e9, brain: { memory: 40, reactionMs: 8000, maxPositions: 5, sizeFrac: 0.15, impulsivity: 0.60, threshold: 0.55, depth: 0.90, stopPct: 0.12, takePct: 0.40, trailPct: 0.20, maxHoldMin: 30, quirk: 'hunt' }, blurb: 'Apex pattern-hunter. Chases momentum and strikes fast.' },
  { id: 'gorilla', name: 'Gorilla', emoji: '🦍', neurons: 33e9, brain: { memory: 30, reactionMs: 15000, maxPositions: 3, sizeFrac: 0.25, impulsivity: 0.50, threshold: 0.60, depth: 0.75, stopPct: 0.20, takePct: 0.60, trailPct: 0.30, maxHoldMin: 50, quirk: 'conviction' }, blurb: 'Big positions, holds through the noise. Strength over speed.' },
  { id: 'chimp', name: 'Chimpanzee', emoji: '🐵', neurons: 28e9, brain: { memory: 35, reactionMs: 10000, maxPositions: 5, sizeFrac: 0.12, impulsivity: 0.55, threshold: 0.55, depth: 0.85, stopPct: 0.12, takePct: 0.35, trailPct: 0.20, maxHoldMin: 30, quirk: 'adaptive' }, blurb: 'Learns mid-match: tightens up after a loss, loosens after a win.' },
  { id: 'dolphin', name: 'Dolphin', emoji: '🐬', neurons: 13e9, brain: { memory: 35, reactionMs: 8000, maxPositions: 5, sizeFrac: 0.12, impulsivity: 0.60, threshold: 0.55, depth: 0.85, stopPct: 0.12, takePct: 0.35, trailPct: 0.20, maxHoldMin: 25, quirk: 'echolocate' }, blurb: 'Reads the flow. Bails the moment the volume goes quiet.' },
  { id: 'dog', name: 'Dog', emoji: '🐕', neurons: 2.3e9, brain: { memory: 15, reactionMs: 10000, maxPositions: 4, sizeFrac: 0.15, impulsivity: 0.70, threshold: 0.50, depth: 0.50, stopPct: 0.15, takePct: 0.40, trailPct: 0.25, maxHoldMin: 40, quirk: 'pack' }, blurb: 'Runs with the pack. Buys what the others hold, stays loyal to winners.' },
  { id: 'pig', name: 'Pig', emoji: '🐷', neurons: 2.2e9, brain: { memory: 12, reactionMs: 12000, maxPositions: 4, sizeFrac: 0.25, impulsivity: 0.70, threshold: 0.45, depth: 0.45, stopPct: 0.25, takePct: 1.00, trailPct: 0, maxHoldMin: 60, quirk: 'greedy' }, blurb: 'Wants the whole 2x. No trailing stop. Pigs get fed, hogs get…' },
  { id: 'raccoon', name: 'Raccoon', emoji: '🦝', neurons: 2.1e9, brain: { memory: 15, reactionMs: 9000, maxPositions: 5, sizeFrac: 0.12, impulsivity: 0.75, threshold: 0.45, depth: 0.50, stopPct: 0.15, takePct: 0.30, trailPct: 0.20, maxHoldMin: 25, quirk: 'shiny' }, blurb: 'Loves shiny things. Paid promotions look like treasure to him.' },
  { id: 'parrot', name: 'Parrot', emoji: '🦜', neurons: 1.6e9, brain: { memory: 12, reactionMs: 10000, maxPositions: 4, sizeFrac: 0.12, impulsivity: 0.70, threshold: 0.50, depth: 0.40, stopPct: 0.15, takePct: 0.30, trailPct: 0.20, maxHoldMin: 30, quirk: 'mimic' }, blurb: 'Copies whoever is winning. Original thoughts not included.' },
  { id: 'crow', name: 'Crow', emoji: '🐦‍⬛', neurons: 1.5e9, brain: { memory: 20, reactionMs: 10000, maxPositions: 4, sizeFrac: 0.12, impulsivity: 0.55, threshold: 0.55, depth: 0.70, stopPct: 0.12, takePct: 0.35, trailPct: 0.20, maxHoldMin: 30, quirk: 'tools' }, blurb: 'Uses tools. Small brain, extra indicators, scary accurate.' },
  { id: 'horse', name: 'Horse', emoji: '🐎', neurons: 1.2e9, brain: { memory: 12, reactionMs: 15000, maxPositions: 3, sizeFrac: 0.08, impulsivity: 0.45, threshold: 0.55, depth: 0.50, stopPct: 0.10, takePct: 0.25, trailPct: 0.15, maxHoldMin: 40, quirk: 'steady' }, blurb: 'Small bets, tight stops, never spooked. Boring on purpose.' },
  { id: 'cat', name: 'Cat', emoji: '🐈', neurons: 760e6, brain: { memory: 10, reactionMs: 12000, maxPositions: 3, sizeFrac: 0.12, impulsivity: 0.40, threshold: 0.50, depth: 0.55, stopPct: 0.12, takePct: 0.30, trailPct: 0.20, maxHoldMin: 30, quirk: 'contrarian' }, blurb: 'Does the opposite of the room. Buys what they just sold.' },
  { id: 'octopus', name: 'Octopus', emoji: '🐙', neurons: 500e6, brain: { memory: 16, reactionMs: 8000, maxPositions: 8, sizeFrac: 0.08, impulsivity: 0.65, threshold: 0.50, depth: 0.60, stopPct: 0.15, takePct: 0.30, trailPct: 0.20, maxHoldMin: 30, quirk: 'multi' }, blurb: 'Eight arms, eight positions. Never all-in on anything.' },
  { id: 'rat', name: 'Rat', emoji: '🐀', neurons: 200e6, brain: { memory: 8, reactionMs: 5000, maxPositions: 5, sizeFrac: 0.10, impulsivity: 0.90, threshold: 0.40, depth: 0.35, stopPct: 0.10, takePct: 0.20, trailPct: 0.15, maxHoldMin: 15, quirk: 'twitchy' }, blurb: 'Fastest reaction in the bracket. Thinks later, if at all.' },
  { id: 'goldfish', name: 'Goldfish', emoji: '🐟', neurons: 10e6, brain: { memory: 3, reactionMs: 7000, maxPositions: 3, sizeFrac: 0.20, impulsivity: 0.80, threshold: 0.35, depth: 0.15, stopPct: 0.20, takePct: 0.30, trailPct: 0, maxHoldMin: 20, quirk: 'forget' }, blurb: 'Three-second memory. Forgets it owns a coin. Buys it again.' },
  { id: 'honeybee', name: 'Honeybee', emoji: '🐝', neurons: 1e6, brain: { memory: 4, reactionMs: 6000, maxPositions: 12, sizeFrac: 0.03, impulsivity: 0.85, threshold: 0.40, depth: 0.30, stopPct: 0.10, takePct: 0.08, trailPct: 0, maxHoldMin: 10, quirk: 'swarm' }, blurb: 'A million neurons, a thousand tiny trades. Death by nectar.' },
].map((a) => Object.assign(a, { stat: a.neurons, statText: fmtNeurons(a.neurons) }));

// MEME CHARACTERS (owner 2026-09-12) — 16 legends of the internet, brains built from their personalities
const MEMES = [
  { id: 'pepe', name: 'Pepe', emoji: '🐸', stat: 98, brain: { memory: 25, reactionMs: 7000, maxPositions: 5, sizeFrac: 0.12, impulsivity: 0.80, threshold: 0.45, depth: 0.60, stopPct: 0.20, takePct: 0.60, trailPct: 0.30, maxHoldMin: 30, quirk: 'contrarian' }, blurb: 'Chaos frog. Buys what you just dumped, because you dumped it. Feels good man.' },
  { id: 'doge', name: 'Doge', emoji: '🐕', stat: 100, brain: { memory: 20, reactionMs: 12000, maxPositions: 3, sizeFrac: 0.25, impulsivity: 0.60, threshold: 0.45, depth: 0.40, stopPct: 0.45, takePct: 2.00, trailPct: 0.60, maxHoldMin: 60, quirk: 'pack' }, blurb: 'Much community. Buys what the pack buys and never, ever sells. Wow.' },
  { id: 'trollface', name: 'Trollface', emoji: '😏', stat: 90, brain: { memory: 20, reactionMs: 8000, maxPositions: 4, sizeFrac: 0.15, impulsivity: 0.60, threshold: 0.50, depth: 0.60, stopPct: 0.15, takePct: 0.40, trailPct: 0.20, maxHoldMin: 40, quirk: 'adaptive' }, blurb: 'Problem? Rewrites his own rules after every trade so nobody can front-run him. Including him.' },
  { id: 'wojak', name: 'Wojak', emoji: '😢', stat: 93, brain: { memory: 10, reactionMs: 9000, maxPositions: 3, sizeFrac: 0.20, impulsivity: 0.85, threshold: 0.40, depth: 0.35, stopPct: 0.06, takePct: 0.15, trailPct: 0.08, maxHoldMin: 20, quirk: 'twitchy' }, blurb: 'Buys the top, sells the bottom, feels every single candle. That feel when.' },
  { id: 'gigachad', name: 'Gigachad', emoji: '🗿', stat: 91, brain: { memory: 15, reactionMs: 6000, maxPositions: 2, sizeFrac: 0.45, impulsivity: 0.70, threshold: 0.50, depth: 0.50, stopPct: 0.35, takePct: 1.00, trailPct: 0.40, maxHoldMin: 60, quirk: 'greedy' }, blurb: 'Two positions, half the stack each, no fear. Sells only at 2x — all of it, jaw first.' },
  { id: 'grumpycat', name: 'Grumpy Cat', emoji: '😾', stat: 88, brain: { memory: 40, reactionMs: 20000, maxPositions: 2, sizeFrac: 0.15, impulsivity: 0.15, threshold: 0.75, depth: 0.80, stopPct: 0.10, takePct: 0.20, trailPct: 0.10, maxHoldMin: 30, quirk: 'grudge' }, blurb: 'NO. Passes on almost everything, and a coin that burned her once is dead to her forever.' },
  { id: 'nyancat', name: 'Nyan Cat', emoji: '🌈', stat: 82, brain: { memory: 6, reactionMs: 3000, maxPositions: 6, sizeFrac: 0.10, impulsivity: 0.90, threshold: 0.40, depth: 0.30, stopPct: 0.08, takePct: 0.12, trailPct: 0.06, maxHoldMin: 8, quirk: 'hunt' }, blurb: 'Pure momentum at rainbow speed. In, out, and gone before the tail fades.' },
  { id: 'badluckbrian', name: 'Bad Luck Brian', emoji: '😬', stat: 78, brain: { memory: 5, reactionMs: 14000, maxPositions: 4, sizeFrac: 0.20, impulsivity: 0.75, threshold: 0.35, depth: 0.20, stopPct: 0.30, takePct: 0.50, trailPct: 0.25, maxHoldMin: 45, quirk: 'echolocate' }, blurb: 'Hears the pump. Arrives after it. Sees almost no signals and trusts all of them.' },
  { id: 'successkid', name: 'Success Kid', emoji: '✊', stat: 84, brain: { memory: 20, reactionMs: 10000, maxPositions: 4, sizeFrac: 0.12, impulsivity: 0.50, threshold: 0.55, depth: 0.60, stopPct: 0.10, takePct: 0.20, trailPct: 0.10, maxHoldMin: 30, quirk: 'steady' }, blurb: 'Small wins, fist pump, repeat. Takes +20% every time and never looks back.' },
  { id: 'harold', name: 'Hide the Pain Harold', emoji: '😅', stat: 86, brain: { memory: 30, reactionMs: 15000, maxPositions: 3, sizeFrac: 0.15, impulsivity: 0.30, threshold: 0.55, depth: 0.60, stopPct: 0.50, takePct: 0.08, trailPct: 0.05, maxHoldMin: 60, quirk: 'forget' }, blurb: 'Smiles through every drawdown, forgets the bag exists, cashes out the moment it turns green.' },
  { id: 'distracted', name: 'Distracted Boyfriend', emoji: '👀', stat: 87, brain: { memory: 8, reactionMs: 6000, maxPositions: 2, sizeFrac: 0.30, impulsivity: 0.90, threshold: 0.40, depth: 0.40, stopPct: 0.20, takePct: 0.30, trailPct: 0.15, maxHoldMin: 10, quirk: 'shiny' }, blurb: 'Always looking at the newer coin. Drops what he holds the second something shinier walks by.' },
  { id: 'harambe', name: 'Harambe', emoji: '🦍', stat: 85, brain: { memory: 30, reactionMs: 15000, maxPositions: 3, sizeFrac: 0.25, impulsivity: 0.50, threshold: 0.60, depth: 0.75, stopPct: 0.30, takePct: 0.70, trailPct: 0.30, maxHoldMin: 60, quirk: 'conviction' }, blurb: 'Holds every bag with both hands and full conviction. Out for him.' },
  { id: 'spongebob', name: 'Mocking SpongeBob', emoji: '🧽', stat: 89, brain: { memory: 12, reactionMs: 9000, maxPositions: 4, sizeFrac: 0.12, impulsivity: 0.70, threshold: 0.45, depth: 0.45, stopPct: 0.15, takePct: 0.35, trailPct: 0.15, maxHoldMin: 30, quirk: 'mimic' }, blurb: 'cOpIeS tHe LeAdEr\'s TrAdEs. Same coins, worse timing, maximum sarcasm.' },
  { id: 'rageguy', name: 'Rage Guy', emoji: '😡', stat: 80, brain: { memory: 8, reactionMs: 5000, maxPositions: 12, sizeFrac: 0.04, impulsivity: 0.95, threshold: 0.35, depth: 0.25, stopPct: 0.15, takePct: 0.25, trailPct: 0.15, maxHoldMin: 25, quirk: 'swarm' }, blurb: 'FFFFFUUUU. A dozen tiny bags and a scream for every one of them.' },
  { id: 'smudge', name: 'Smudge the Cat', emoji: '🐱', stat: 83, brain: { memory: 16, reactionMs: 8000, maxPositions: 8, sizeFrac: 0.08, impulsivity: 0.65, threshold: 0.50, depth: 0.45, stopPct: 0.20, takePct: 0.30, trailPct: 0.20, maxHoldMin: 40, quirk: 'multi' }, blurb: 'Confused, at a table, holding eight coins he does not understand. He did not order any of this.' },
  { id: 'shrek', name: 'Shrek', emoji: '👹', stat: 92, brain: { memory: 30, reactionMs: 18000, maxPositions: 3, sizeFrac: 0.20, impulsivity: 0.35, threshold: 0.60, depth: 0.90, stopPct: 0.15, takePct: 0.50, trailPct: 0.25, maxHoldMin: 50, quirk: 'tools' }, blurb: 'Ogres have layers. So does his chart. Slow out of the swamp, sees everything once he is.' },
].map((m) => Object.assign(m, { statText: 'meme power ' + m.stat }));

module.exports = {
  animals: { id: 'animals', name: 'ANIMAL KINGDOM', tagline: '16 animals · brains scaled to their real neuron counts', traders: ANIMALS },
  memes: { id: 'memes', name: 'MEME CHARACTERS', tagline: '16 legends of the internet · brains built from their personalities', traders: MEMES },
};
